# Generated by Django 2.1.7 on 2019-03-11 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_paste'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_expired',
            field=models.DateTimeField(blank=True, default='2020-01-01'),
        ),
        migrations.AddField(
            model_name='post',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paste',
            name='date_expired',
            field=models.DateTimeField(blank=True),
        ),
    ]
